all : PROYECTO2.ARQ.asm
	dosbox -c 'ml PROYECTO2.ARQ/PROYECTO2.ARQ.asm' -c 'PROYECTO2.ARQ.exe'

debug : PROYECTO2.ARQ.asm
	dosbox -c 'ml PROYECTO2.ARQ/PROYECTO2.ARQ.asm' -c 'debug PROYECTO2.ARQ.exe'
